---
- hosts: all
  become_user: yes
  tasks:
    - name: Install git and notepad++
      win_chocolatey:
        name:
        - git
        - notepadplusplus
        state: absent

    - name: Install VS Code and PowerShell Preview
      win_chocolatey:
        name:
        - vscode.install
        - powershell-preview
        state: absent