---
- hosts: all
  become_user: yes
  tasks:
    - name: Print config
      vars:
        msg: |
          Success on:
          - Creating {{ ad_firstname }} user with Administrative right
          - Creating the following folders for the {{ad_firstname}} user:
                   - 'C:\Users\{{ ad_firstname }}\Desktop\ansible'
                   - 'C:\Users\{{ ad_firstname }}\Desktop\ansible\collections'
                   - 'C:\Users\{{ ad_firstname }}\Desktop\ansible\roles'
          - Installing following using Windows Chocolatey Package Manager:
                   - GIT
                   - Notepad++
          - Updating all the packages managed by Windows Chocolatey Package Manager
      debug:
        msg: "{{ msg.split('\n')}}"