---
- name: Create a file and push it in GIT repo
  hosts: localhost
  gather_facts: no
  collections:
    - lvrfrc87.git_acp
  vars:
    repo_url: "https://github.com/AkashMainali/AAP-Windows-demo.git"
    tmp_repo_directory: "/var/tmp/ansible"
  tasks:
    - name: Generate report
      ansible.builtin.template:
        src: report.j2
        dest: /var/tmp/ansible_file
        mode: "0755"

    # - name: Clone Git repo
    #   ansible.builtin.shell: |
    #     "git clone {{ repo_url }}"
    #     expect "Username for 'https://github.schonfeld.com':"
    #     send "{{ git_username }}\n"
    #     expect "Password for 'https://amainali@schonfeld.com@github.schonfeld.com':"
    #     send "{{ git_password }}"
    #   args:
    #     chdir: "/var/tmp/"

    - name: Clone GIT Repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ tmp_repo_directory }}"
        clone: yes
        update: yes

    - name: copy folders
      ansible.builtin.copy:
        dest: "{{ tmp_repo_directory }}/AAP-Windows-demo/"
        src: "/var/tmp/ansible_file"
        force: true

    # - name: Push the Git repo
    #   ansible.builtin.shell: |
    #     git config --global user.email amainali868@gmail.com
    #     git config --global user.name akashmainali
    #     git add -A && git commit -m "RHAAP: Automated Commit by Ansible  " && git push
    #   args:
    #     chdir: "{{ tmp_repo_directory }}"
    #   register: output
    #   failed_when: >
    #     output.msg != "" and
    #     ("error" in output.msg or
    #     "conflict" in output.msg or
    #     "Errno" in output.msg or
    #     "fatal" in output.msg or
    #     (output.stdout != "" and
    #     "nothing to commit, working tree clean" not in output.stdout) or
    #     (output.stderr != ""))`

    - name: Entering git details
      ansible.builtin.shell: |
        git config --global user.email "amainali868@gmail.com"
        git config --global user.name "Akash Mainali"
        
    - name: HTTPS | push all changes
      git_acp:
        # mode: https
        # user: "{{ git_username }}"
        # token: "{{ git_password }}"
        path: "/var/tmp/ansible/AAP-Windows-demo/"
        branch: main
        comment: " Add all the things."
        add: [ "." ]
        url: "https://github.com/AkashMainali/AAP-Windows-demo.git"

    # - name: Push the Git repo
    #   ansible.builtin.shell: |
    #     git config --global user.email "amainali868@gmail.com"
    #     git config --global user.name "Akash Mainali"
    #     git add -A && git commit -m "RHAAP: Automated Commit by Ansible  " && git push
    #   args:
    #     chdir: "{{ tmp_repo_directory }}"
    #   register: output
    #   failed_when: >
    #     output.msg != "" and
    #     ("error" in output.msg or
    #     "conflict" in output.msg or
    #     "Errno" in output.msg or
    #     "fatal" in output.msg or
    #     (output.stdout != "" and
    #     "nothing to commit, working tree clean" not in output.stdout) or
    #     (output.stderr != ""))