---
# Start a website
- name: Copy the website files and folders
  win_copy:
    src: romofyi-html
    dest: C:\sites

- name: Remove Default Web Site
  community.windows.win_iis_website:
    name: "Default Web Site"
    state: absent
    
- name: Deploy a new IIS site
  community.windows.win_iis_website:
    name: Romify
    state: started
    port: 80
    ip: 127.0.0.1
    hostname: "{{ windows_hostname }}"
    physical_path: C:\sites\romofyi-html\index.html
    parameters: logfile.directory:C:\sites\logs
  register: website

- name: Deploy new WebApp
  community.windows.win_iis_webapplication:
    name: api
    site: acme
    state: present
    physical_path: C:\apps\acme\api


