---
# Start a website
- name: Copy the website files and folders
  win_copy:
    src: romofyi-html
    dest: C:\sites

- name: Remove Default Web Site
  community.windows.win_iis_website:
    name: "Default Web Site"
    state: absent
    
- name: Deploy a new IIS site
  community.windows.win_iis_website:
    name: Default Web Site
    state: started
    port: 80
    ip: 127.0.0.1
    physical_path: C:\sites\romofyi-html\index.html
    parameters: logfile.directory:C:\sites\logs
  register: website

