---
# tasks file for create_windows_vm
- name: Select Windows 2016 template
  set_fact:
      windows_template: "windows_2016_template"
  when: vm_template == "Windows_2016"

- name: Select Windows 2019 template
  set_fact:
      windows_template: "windows_2019_template"
  when: vm_template == "Windows_2019"

- name: Provision Windows machine
  vmware_guest:
    folder: "Windows-Automation"
    template: windows_2016_template
    validate_certs: no
    name: "{{ vm_name }}"
    state: poweredon
    cluster: "Windows-Automation"
    datastore: "Demo-Datastore01"
    datacenter: "Plainview"
    hostname: "cmrv-vc01.crucible.iisl.com"
    username: "bmuggalla@CRUCIBLE.IISL.COM"
    password: "Temp!234"
    hardware:
      memory_mb: 4096
      num_cpus: 2
    networks:
     - name: "Windows-Automation - vLAN 102"
       type: dhcp
       domain: "{{ vm_name }}.iisl.lab"
       dns_servers:
         - 192.168.2.201
    customization:
       hostname: '{{ vm_name }}.iisl.lab'
       dns_servers:
         - 192.168.2.201
       autologon: yes
       dns_suffix:
         - "crucible.iisl.lab"
         - "iisl.lab"
       domain: 'iisl.lab'
       state: started
       runonce:
         - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
    wait_for_ip_address: yes
    wait_for_customization: yes
  delegate_to: localhost
  register: windows_vm

- name: debug ip address of vm created
  set_fact:
    windows_vm_ip: "{{ windows_vm.instance.hw_eth0.ipaddresses[0] }}"  #hel_vm.instance.ipv4

- name: Displaying success message
  debug:
    msg: "The VM Has been provisioned successfully"

- name: Set stats for workflow template
  set_stats:
    data:
      windows_ip_address: "{{ windows_vm_ip }}"
      windows_hostname: "{{ vm_name }}.iisl.lab"
