---
# tasks file for create_linux_vm
- name: Select Windows 2016 template
  set_fact:
      windows_template: "windows2016_template"
  when: vm_template == "Windows_2016"

- name: Select Windows 2019 template
  set_fact:
      windows_template: "windows_2019_template"
  when: vm_template == "Windows_2019"

- name: Provision Windows machine
  vmware_guest:
    folder: "RHEL-Automation"
    template: "{{ windows_template }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: poweredon
    cluster: "RHEL-Automation"
    datastore: "Demo-Datastore01"
    datacenter: "Plainview"
    networks:
     - name: "RHEL-Automation - vLAN 102"
       type: dhcp
       domain: "{{ vm_name }}.iisl.lab"
       dns_servers:
         - 192.168.2.201
    customization:
       dns_suffix:
         - "crucible.iisl.lab"
         - "iisl.lab"
       dns_servers:
         - '192.168.2.201'
       domain: 'iisl.lab'
       state: started
    wait_for_ip_address: yes
    wait_for_customization: yes
  register: windows_vm

- name: debug ip address of vm created
  set_fact:
    linux_vm_ip: "{{ windows_vm.instance.hw_eth0.ipaddresses[0] }}"  #hel_vm.instance.ipv4

- name: Displaying success message
  debug:
    msg: "The VM Has been provisioned successfully"

- name: Set stats for workflow template
  set_stats:
    data:
      linux_ip_address: "{{ windows_vm_ip }}"
      linux_hostname: "{{ vm_name }}.iisl.lab"
