---
# tasks file for install_choco_windows
- name: Call task file to install chocolatey
  include_tasks: install_chocolatey.yml

- name: Install git
  win_chocolatey:
    name: git
    state: absent

- name: install and pin Notepad++ at 7.6.3
  win_chocolatey:
    name: notepadplusplus
    version: 7.6.3
    pinned: yes
    state: present
    
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest